[package]
name = "battle_sheep_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
either = "1.9.0"
next-gen = "0.0.10"
